# SPDX-License-Identifier: Apache-2.0
# Stub: TTFont and its tables as this tree reads them (W255). A font's tables
# (head, hhea, OS/2, glyf, ...) are records whose attributes depend on the table, so
# Table is declared dynamic (attribute and item access); nothing else here is.
from collections.abc import Iterator
from os import PathLike
from typing import Any

class Table:
    def __getattr__(self, name: str) -> Any: ...
    def __getitem__(self, key: str) -> Table: ...
    def draw(self, pen: Any) -> None: ...

class TTFont:
    def __init__(self, file: str | PathLike[str] | None = None) -> None: ...
    def __getitem__(self, tag: str) -> Table: ...
    def __contains__(self, tag: str) -> bool: ...
    def getGlyphSet(self) -> dict[str, Table]: ...
    def getGlyphOrder(self) -> list[str]: ...
    def getBestCmap(self) -> dict[int, str]: ...
    def keys(self) -> list[str]: ...
    def __iter__(self) -> Iterator[str]: ...
    def save(self, file: str | PathLike[str] | Any) -> None: ...
