# SPDX-License-Identifier: Apache-2.0
# Stub: TTGlyphPen as make_font uses it (W255). glyph() returns a glyf-table Glyph.
from fontTools.ttLib import Table

class TTGlyphPen:
    def __init__(self, glyphSet: None) -> None: ...
    def moveTo(self, pt: tuple[int, int]) -> None: ...
    def lineTo(self, pt: tuple[int, int]) -> None: ...
    def closePath(self) -> None: ...
    def glyph(self) -> Table: ...
