#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Mike Mol
"""make_tokens.py — the palette as W3C DTCG design tokens: the interchange read of the one solve (W160).

⚑ ONE FILE, TWO CONSUMERS. Design tools (Figma/Penpot token importers, Style
Dictionary) read DTCG, and the engine adapters (W151 -> W154-W157) read the same
file: the codomain census (W42) ranked this the highest-reach gap. A second
material-spec emitter was audited and refused (W151/W160 collapse): engines get a
`material` group INSIDE this file (W151), not another file.

    make_tokens.py            # write catalog/el-openglo.tokens.json
    make_tokens.py --print    # the token document to stdout

WHAT IT EMITS. One top-level group per variant, `{"$description", "color": {...},
"alpha": {...}}`: every emitted RGB token as `{"$type": "color", "$value": "#rrggbb"}`
and the two solved ghost alphas as `{"$type": "number", "$value": x}`. Names are the
token keys (palette_graph.NODES relates them), exactly as make_css uses them.

⚑ NO COLOUR IS COMPUTED HERE. Every value is read from make_schemes.GRID, the emitted
authority (scripts/check_token_source refuses an emitter that reads none).

WEAKNESS, STATED. Colours and alphas only: no geometry, bloom or stroke weight, and
no composite ("seen") ghost - DTCG has no colour-mix type, so a consumer composites
fg_in over view at ghost_alpha itself (relations.md §3b). The material group is W151.
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(ROOT, "catalog", "el-openglo.tokens.json")
ALPHAS = ("ghost_alpha", "ghost_alpha_glanced")


def _is_rgb(v):
    parts = str(v).split(",")
    return len(parts) == 3 and all(p.strip().isdigit() for p in parts)


def _hex(v):
    r, g, b = (int(p) for p in str(v).split(","))
    return f"#{r:02x}{g:02x}{b:02x}"


def tokens():
    """{variant_id: token dict} - read from make_schemes.GRID, the emitted authority."""
    sys.path.insert(0, ROOT)
    import make_schemes
    out = {}
    for value in make_schemes.GRID.values():
        t = value[0] if isinstance(value, (list, tuple)) else value
        if isinstance(t, dict) and "id" in t:
            out[t["id"]] = t
    return out


def group(t):
    """One variant as a DTCG group: colours and the solved alphas, nothing invented."""
    color = {k: {"$type": "color", "$value": _hex(t[k])} for k in sorted(t) if _is_rgb(t[k])}
    alpha = {k: {"$type": "number", "$value": round(float(t[k]), 4)} for k in ALPHAS if k in t}
    return {"$description": f"{t.get('name', t['id'])} - solved by make_palette, emitted by make_schemes",
            "color": color, "alpha": alpha}


def document():
    toks = tokens()
    if not toks:
        raise SystemExit("make_tokens: the grid is empty - nothing to emit")
    doc = {"$description": "el-openglo - the solved palette as W3C DTCG design tokens. "
                           "GENERATED by make_tokens.py from make_schemes.GRID; do not hand-edit."}
    for vid in sorted(toks):
        doc[vid] = group(toks[vid])
    return doc


def main(argv):
    for a in argv[1:]:
        if a != "--print":
            print(f"make_tokens: unknown flag {a!r}", file=sys.stderr)
            return 2
    text = json.dumps(document(), indent=2, sort_keys=True) + "\n"
    if "--print" in argv:
        sys.stdout.write(text)
        return 0
    from emitters import atomic_write
    atomic_write(OUT, text)
    print(f"make_tokens: wrote {os.path.relpath(OUT, ROOT)} ({len(tokens())} variants)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
