#!/usr/bin/env python3
"""make_css.py — the palette as CSS custom properties: the web's read of the one solve.

⚑ THE LOWEST-COMMON-DENOMINATOR SINK.  Union's input is CSS, the browser themes
are colour maps, and a site's theme is a stylesheet: emitting the solved palette
ONCE as custom properties gives every one of those a shared read, and makes the
palette linkable (rel=stylesheet) from the operator's IndieWeb site (W19).

    make_css.py            # write catalog/el-openglo.css
    make_css.py --print    # the stylesheet to stdout

WHAT IT EMITS.  For every variant, a block `[data-el-variant="<id>"]` carrying
one `--el-<key>` per emitted token, with the key hyphenated and the value as
`rgb(r g b)`; the two solved alphas as plain numbers; and the SEEN ghost as one
CSS expression, `color-mix()` of fg_in over view at the alpha — so relations.md
§3b's identity (seen = composite(declared, ground, α)) is stated in the sink,
not re-derived by every consumer. `:root` defaults to EL-Openglo, and
`prefers-color-scheme: light` selects its Lit (backlit) form — the palette's own
Off/Lit polarity mapped onto the web's dark/light.

⚑ NAMES ARE THE TOKEN KEYS, NOT INVENTED.  `--el-fg-in`, not `--el-ghost`:
palette_graph.NODES is the one place a role's names are related, and this file
adds none. A consumer wanting "the ghost" reads §3 of relations.md and finds
fg_in; that is the point.

WEAKNESS, STATED.  This emits colours and alphas. It emits no geometry, no bloom,
no stroke weight — the three lit/ghost channels the segment surfaces carry are
not expressible as custom properties without a consumer to define them.
"""
import os
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(ROOT, "catalog", "el-openglo.css")
DEFAULT = "EL-Openglo"


def _is_rgb(v):
    parts = str(v).split(",")
    return len(parts) == 3 and all(p.strip().isdigit() for p in parts)


def _prop(key):
    return "--el-" + key.replace("_", "-")


def tokens():
    """{variant_id: token dict} — read from make_schemes.GRID, the emitted authority."""
    sys.path.insert(0, ROOT)
    import make_schemes
    out = {}
    for value in make_schemes.GRID.values():
        t = value[0] if isinstance(value, (list, tuple)) else value
        if isinstance(t, dict) and "id" in t:
            out[t["id"]] = t
    return out


def block(t):
    """The declarations for one variant, one custom property per token."""
    lines = []
    for key in sorted(t):
        v = t[key]
        if _is_rgb(v):
            r, g, b = (p.strip() for p in str(v).split(","))
            lines.append(f"  {_prop(key)}: rgb({r} {g} {b});")
        elif key in ("ghost_alpha", "ghost_alpha_glanced"):
            lines.append(f"  {_prop(key)}: {float(v):.3f};")
        elif key in ("ghost_alpha_glanced_infeasible", "tt_is_sel"):
            lines.append(f"  {_prop(key)}: {str(v).lower()};")
        # name/id and other prose tokens are not CSS values; they are omitted, not
        # coerced — the witness counts colour + alpha keys, which is the contract
    # the SEEN ghost, per parsing mode — the §3b identity as one expression
    lines.append("  --el-fg-in-seen: color-mix(in srgb, var(--el-fg-in) "
                 "calc(var(--el-ghost-alpha) * 100%), var(--el-view));")
    lines.append("  --el-fg-in-seen-glanced: color-mix(in srgb, var(--el-fg-in) "
                 "calc(var(--el-ghost-alpha-glanced) * 100%), var(--el-view));")
    return "\n".join(lines)


def stylesheet():
    toks = tokens()
    if not toks:
        raise SystemExit("make_css: the grid is empty — nothing to emit")
    if DEFAULT not in toks or DEFAULT + "-Lit" not in toks:
        raise SystemExit(f"make_css: {DEFAULT} and {DEFAULT}-Lit must both exist")
    parts = [
        "/* el-openglo — the solved palette as CSS custom properties.",
        " * GENERATED by make_css.py from make_schemes.GRID; do not hand-edit.",
        " * One block per variant; :root is EL-Openglo, and prefers-color-scheme: light",
        " * selects its backlit (Lit) form. The seen ghost is stated as color-mix()",
        " * over the ground at the solved alpha (catalog/relations.md §3b, §3c). */",
        "",
        f":root {{\n{block(toks[DEFAULT])}\n}}",
        "",
        f"@media (prefers-color-scheme: light) {{\n:root {{\n{block(toks[DEFAULT + '-Lit'])}\n}}\n}}",
        "",
    ]
    for vid in sorted(toks):
        parts.append(f'[data-el-variant="{vid}"] {{\n{block(toks[vid])}\n}}')
        parts.append("")
    return "\n".join(parts)


def main(argv):
    known = {"--print"}
    for a in argv[1:]:
        if a not in known:
            print(f"make_css: unknown flag {a!r}", file=sys.stderr)
            return 2
    css = stylesheet()
    if "--print" in argv:
        sys.stdout.write(css)
        return 0
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(css)
    print(f"make_css: wrote {os.path.relpath(OUT, ROOT)} ({len(tokens())} variants)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
