#!/usr/bin/env python3
"""make_union.py — the palette as a KDE Union style: Breeze, with its alphas SOLVED.

⚑ WHAT UNION ALREADY GETS FROM US, AND WHAT IT AUTHORS.  Union (kde-plasma/union,
the styling engine replacing Breeze's QQC2/Kirigami code) reads every COLOUR
through `custom-color("kcolorscheme", ...)` — i.e. from the active .colors
file, which make_schemes emits. Colours need no emitter. What Breeze's
`variables.css` AUTHORS is the ALPHAS it composes those colours at: an
indicator is "window text at 0.4", a hover fill is "highlight at 0.3", the
focus ring "decoration-focus at 0.3". Those are the ghost relation with the
number guessed. This repo solves that relation (relations.md §3b/§3c): the
smallest alpha at which a foreground composited over its ground still clears
the parsing-mode floor — `ghost_solve.alpha_min(fg, ground, floor)`.

    make_union.py                 # emit union/<variant>/{style.css,overrides.css} for every variant
    make_union.py --alphas        # the solved alphas per variant, and which are OPEN

⚑ ONE STYLE PER VARIANT, because the alphas are per variant (the colour pairs
differ) while Union cannot read our [EL] keys from kcolorscheme. The style
is `@import "../breeze/style.css"` + `overrides.css` — the shape Union's own
breeze-mobile and breeze-rtl use — so everything Breeze draws stays Breeze
and only the solved variables move. Selection is `UNION_STYLE_NAME=<style>`
(libUnion, 6.7.5; no config file yet), which el-openglo-apply writes to
~/.config/plasma-workspace/env/ — effective at the next login.

⚑ WHAT IS SOLVED AND WHAT IS OPEN — stated, not smoothed over:
  --indicator-color         window text over window bg, LOOKED-AT floor   (Breeze 0.4)
  --focus-outline-alpha     decoration-focus over window bg, LOOKED-AT     (Breeze 0.3)
  --highlight-hover-color   highlight over window bg, GLANCED-AT floor     (Breeze 0.3)
  --card-hover-color        highlight mixed into view bg, GLANCED-AT       (Breeze mix 0.1)
  OPEN (kept as Breeze authored): --indicator-press-color 0.7,
  --indicator-current-color 0.95, --card-pressed-color mix 0.3, --shadow-color
  0.1, --window/view-highlight mix 0.5 — the palette has no relation for a
  PRESSED state or a shadow yet (relations.md §3d lists them).

WEAKNESS. Without the engine running there is no check that Union's cascade
applies a later :root the way CSS does; check_union.py parses the emitted CSS
and asserts every overridden variable exists in Breeze's variables.css and
every value is a solved number — the ruleinspector arm is a SKIP until
USE=tools. The look waits for a session restart.
"""
import os
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, ROOT)

VARIANTS = ["EL-Openglo", "EL-Openglo-Lit", "EL-Azure", "EL-Azure-Lit",
            "EL-Amber", "EL-Amber-Lit"]

# (union variable, foreground role, ground role, parsing mode, Breeze's authored value)
SOLVED = (
    ("--indicator-color",       "window_fg", "ground",  "looked",  0.4),
    ("--focus-outline-alpha",   "focus",     "ground",  "looked",  0.3),
    ("--highlight-hover-color", "sel",       "ground",  "glanced", 0.3),
    ("--card-hover-color",      "sel",       "view_bg", "glanced", 0.1),
)
# Breeze variables this style leaves as authored, each with why
OPEN = {
    "--indicator-press-color": "a PRESSED state: no relation solves it (Breeze 0.7)",
    "--indicator-current-color": "the current indicator is nearly lit (Breeze 0.95); no relation",
    "--card-pressed-color": "a PRESSED state (Breeze mix 0.3)",
    "--shadow-color": "a shadow, not a ghost (Breeze 0.1)",
    "--window-highlight-color": "a 0.5 mix with no floor to solve against",
    "--view-highlight-color": "a 0.5 mix with no floor to solve against",
}


def _rgb(hexs):
    hexs = hexs.lstrip("#")
    return tuple(int(hexs[i:i + 2], 16) for i in (0, 2, 4))


def alphas(variant):
    """{union var: (alpha or None, fg hex, ground hex, floor, breeze)} for a variant."""
    import make_preview as MP
    import ghost_solve as GS
    import cvd_gate as C
    cols = MP.parse_scheme(variant)
    out = {}
    for var, fg_role, gnd_role, mode, breeze in SOLVED:
        floor = C.GHOST_VISIBLE_LC if mode == "looked" else C.GHOST_VISIBLE_LC_GLANCED
        a = GS.alpha_min(_rgb(cols[fg_role]), _rgb(cols[gnd_role]), floor)
        # round UP at three places: the floor is a minimum, and a value rounded
        # below it would be the check passing on a number the screen fails
        a = None if a is None else min(1.0, (int(a * 1000) + (a * 1000 % 1 > 0)) / 1000)
        out[var] = (a, cols[fg_role], cols[gnd_role], floor, breeze)
    return out


def style_name(variant):
    return "el-openglo-" + variant.lower()


def style_css(variant):
    return ("/* EL Openglo — %s. Breeze, with its composited alphas solved by the palette.\n"
            " * Generated by make_union.py; edit the relation, not this file. */\n"
            "@import \"../breeze/style.css\";\n"
            "@import \"overrides.css\";\n" % variant)


def overrides_css(variant):
    rows = alphas(variant)
    lines = [f"/* {variant}: alphas solved by ghost_solve.alpha_min over the scheme's own pairs;",
             " * OPEN variables are left as Breeze authored — see make_union.OPEN. */",
             ":root {"]
    for var, (a, fg, gnd, floor, breeze) in rows.items():
        if a is None:
            lines.append(f"    /* {var}: UNSOLVABLE — {fg} over {gnd} cannot clear Lc {floor}; Breeze {breeze} kept */")
            continue
        note = f"/* {fg} over {gnd}, floor Lc {floor}; Breeze {breeze} */"
        if var == "--focus-outline-alpha":
            lines.append(f"    {var}: {a}; {note}")
            # Breeze defines --focus-color THROUGH this variable; restate it in
            # case the engine resolved var() when it parsed Breeze
            lines.append(f"    --focus-color: modify-color(custom-color(\"kcolorscheme\", \"active\", "
                         f"\"window\", \"decoration\", \"focus\") set-alpha {a});")
        elif var == "--indicator-color":
            lines.append(f"    {var}: modify-color(var(--window-text-color) set-alpha {a}); {note}")
        elif var == "--highlight-hover-color":
            lines.append(f"    {var}: modify-color(var(--highlight-color) set-alpha {a}); {note}")
        elif var == "--card-hover-color":
            lines.append(f"    {var}: mix(var(--card-background-color), var(--highlight-color), {a}); {note}")
    lines.append("}")
    return "\n".join(lines) + "\n"


def render_all(variants, out_map):
    """Write style.css + overrides.css into out_map[variant] for each variant."""
    written = []
    for v in variants:
        d = out_map[v]
        os.makedirs(d, exist_ok=True)
        for name, body in (("style.css", style_css(v)), ("overrides.css", overrides_css(v))):
            p = os.path.join(d, name)
            open(p, "w", encoding="utf-8").write(body)
            written.append(p)
    return written


if __name__ == "__main__":
    if "--alphas" in sys.argv:
        for v in VARIANTS:
            print(v)
            for var, (a, fg, gnd, floor, breeze) in alphas(v).items():
                print(f"  {var:26} {'OPEN' if a is None else a:>6}  ({fg} over {gnd}, Lc>={floor}; Breeze {breeze})")
        for var, why in OPEN.items():
            print(f"  OPEN {var}: {why}")
        sys.exit(0)
    outs = {v: os.path.join(ROOT, "union", style_name(v)) for v in VARIANTS}
    w = render_all(VARIANTS, outs)
    print(f"make_union: wrote {len(w)} files for {len(VARIANTS)} styles under union/")
