#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Mike Mol
"""make_android_clock.py — the segment clock as per-variant JSON, for a renderer that is not Plasma (W193).

An Android live wallpaper or widget cannot read a Plasma scheme or a QML template. What it
needs is DATA: this variant's colours, the seven-segment geometry, the digit masks and the
module metrics. This emits that, one file per variant, so the Android port (W122) draws
the clock from the same sources the plasmoid and the wallpapers do.

    make_android_clock.py            # write catalog/android/clock/<variant>.json
    make_android_clock.py --print    # the variant documents to stdout

⚑ NO COLOUR OR GEOMETRY IS COMPUTED HERE. Every field names the authority it is read from
(the document's own `sources` table), and scripts/check_android_clock.py holds each value to it:

  palette.lit/ghost/hot/ground   make_schemes.GRID, through make_tokens.tokens() - the roles
                                 make_clock binds (fg, fg_in, fg_act) and the view ground
  palette.ghost_alpha(_glanced)  the same token dict (make_palette solved them)
  geometry.segGeom / digSegs     segment_topology.seg7_svg_grid / glyph7_letters, as make_clock
  geometry.metrics               segment_topology.metrics(1.0): lengths as ratios of digit height
  display                        display_types.registry_for("7"), the display registry's 7-seg tables

WEAKNESS, STATED. It proves the JSON carries what its authorities say today, not that any
Android renderer draws it; the geometry is the clock's coarse 2x3 cell, so a 16-segment face
would need `display` for a different key. Colours are the lit-on-void Off variants' and the
Lit variants' own tokens - no Monet seeding (catalog/android.md measures that separately).
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(ROOT, "catalog", "android", "clock")
SCHEMA = "el-android-clock/1"
# palette role -> the make_schemes.GRID token it is read from (make_clock: lit/ghost/hot are
# the scheme's fg / fg_in / fg_act; ground is the View ground, make_tokens.MATERIAL base)
ROLES = {"lit": "fg", "ghost": "fg_in", "hot": "fg_act", "ground": "view"}
ALPHAS = ("ghost_alpha", "ghost_alpha_glanced")
SOURCES = {
    "palette": "make_schemes.GRID via make_tokens.tokens()",
    "geometry.segGeom": "segment_topology.seg7_svg_grid()",
    "geometry.digSegs": "segment_topology.glyph7_letters()",
    "geometry.metrics": "segment_topology.metrics(1.0)",
    "display": "display_types.registry_for('7')",
}


def tokens():
    """{variant_id: token dict} - make_tokens.tokens(), itself read from make_schemes.GRID."""
    sys.path.insert(0, ROOT)
    import make_tokens
    return make_tokens.tokens()


def _hex(v):
    import make_tokens
    return make_tokens._hex(v)


def geometry():
    """The variant-independent geometry: the coarse 7-seg cell, digit masks, metrics."""
    sys.path.insert(0, ROOT)
    import segment_topology as ST
    return {"cell": [2, 3],
            "segGeom": {k: [v[0], v[1], v[2]] for k, v in ST.seg7_svg_grid().items()},
            "digSegs": {ch: ST.glyph7_letters(ch) for ch in "0123456789"},
            "metrics": {k: v for k, v in ST.metrics(1.0).items()}}


def display():
    sys.path.insert(0, ROOT)
    import display_types
    return display_types.registry_for("7")


def document(t):
    """One variant's clock document, every value read from its authority."""
    for k in list(ROLES.values()) + list(ALPHAS):
        if k not in t:
            raise SystemExit(f"make_android_clock: {t['id']} has no token {k!r}")
    palette = {role: _hex(t[key]) for role, key in ROLES.items()}
    for a in ALPHAS:
        palette[a] = round(float(t[a]), 4)
    return {"schema": SCHEMA, "variant": t["id"], "name": t.get("name", t["id"]),
            "description": "GENERATED by make_android_clock.py; do not hand-edit.",
            "palette": palette, "geometry": geometry(), "display": display(),
            "sources": dict(SOURCES)}


def documents():
    """{filename: text} - one JSON file per declared variant."""
    toks = tokens()
    if not toks:
        raise SystemExit("make_android_clock: the grid is empty - nothing to emit")
    return {f"{vid}.json": json.dumps(document(toks[vid]), indent=2, sort_keys=True) + "\n"
            for vid in sorted(toks)}


def main(argv):
    for a in argv[1:]:
        if a != "--print":
            print(f"make_android_clock: unknown flag {a!r}", file=sys.stderr)
            return 2
    docs = documents()
    if "--print" in argv:
        for name, text in docs.items():
            sys.stdout.write(text)
        return 0
    from emitters import atomic_write
    os.makedirs(OUT_DIR, exist_ok=True)
    for name, text in docs.items():
        atomic_write(os.path.join(OUT_DIR, name), text)
    print(f"make_android_clock: wrote {len(docs)} file(s) under {os.path.relpath(OUT_DIR, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
