# METADATA
# title: "S0 — no planned stills admits nothing"
# description: |
#   The measurement is `scripts/check_screens.py --json` over the plan
#   catalog/library/render_screens.py declares (five surfaces x six variants).
package el.screens

import rego.v1

deny contains msg if {
	count(input.screens) == 0
	msg := "S0: no stills are planned"
}

# METADATA
# title: "S1 — every planned still exists"
# description: |
#   The pictures are checked in and regenerated by one script; an emitter change
#   without a regeneration, or a render that produced no file, fails here.
deny contains msg if {
	some s in input.screens
	not s.exists
	msg := sprintf("S1: %s is missing", [s.file])
}

# METADATA
# title: "S2 — a still is not blank"
# description: |
#   A render that drew nothing is one colour. The clock alone on its ground still
#   has lit, ghost and ground; a picture with fewer than three distinct colours
#   drew no surface.
deny contains msg if {
	some s in input.screens
	s.exists
	s.distinct < 3
	msg := sprintf("S2: %s has %d distinct colour(s) — nothing was drawn", [s.file, s.distinct])
}

# METADATA
# title: "S3 — a still sits on its variant's ground"
# description: |
#   The modal colour of a still is the variant's Window background (the harness's
#   window, where the clock and switcher sit) or its View background (what a
#   bound wallpaper or marquee draws as its own void). Anything else means the
#   picture was rendered under the wrong scheme.
deny contains msg if {
	some s in input.screens
	s.exists
	not s.modal in s.grounds
	msg := sprintf("S3: %s has modal colour %s, not one of %v (variant %s)", [s.file, s.modal, s.grounds, s.variant])
}
