# METADATA
# title: "S0 — no planned stills admits nothing"
# description: |
#   The measurement is `scripts/check_screens.py --json` over the plan
#   catalog/library/render_screens.py declares (five surfaces x six variants).
#
#   ⚑ EVERY STILL AND ANIMATION LANDS IN EXACTLY ONE OF withheld / deny / admitted.
#   render_screens.measure ALWAYS emits `exists` (a boolean) and, when it is true,
#   `distinct` / `modal` / `grounds` for a still and `frames` / `tears` /
#   `seamless` for an animation; the population always carries `animations`.
#   Null or absent is "could not say": S7 withholds it and no rule judges it.
package el.screens

import rego.v1

missing(obj, fields) := {f | some f in fields; object.get(obj, f, null) == null}

still_missing(s) := m if {
	object.get(s, "exists", null) == true
	m := missing(s, ["distinct", "modal", "grounds"])
} else := missing(s, ["exists"])

anim_missing(a) := m if {
	object.get(a, "exists", null) == true
	m := missing(a, ["frames", "tears", "seamless"])
} else := missing(a, ["exists"])

stills := [s | some s in object.get(input, "screens", []); count(still_missing(s)) == 0]

anims := [a | some a in object.get(input, "animations", []); count(anim_missing(a)) == 0]

deny contains msg if {
	count(object.get(input, "screens", [])) == 0
	msg := "S0: no stills are planned"
}

deny contains x.msg if some x in case_deny

# METADATA
# title: "S7 — a fact the measurement did not state is withheld, not judged"
withheld contains msg if {
	some s in object.get(input, "screens", [])
	some f in still_missing(s)
	msg := sprintf("S7: %v: %s was not measured", [object.get(s, "file", null), f])
}

withheld contains msg if {
	some a in object.get(input, "animations", [])
	some f in anim_missing(a)
	msg := sprintf("S7: %v: %s was not measured", [object.get(a, "file", null), f])
}

withheld contains "S7: animations was not measured" if {
	object.get(input, "animations", null) == null
}

# the stills and animations judged and passed
admitted contains s.file if {
	some s in array.concat(stills, anims)
	not denied_file(s.file)
}

denied_file(f) if {
	some x in case_deny
	x.file == f
}

# METADATA
# title: "S1 — every planned still exists"
# description: |
#   The pictures are checked in and regenerated by one script; an emitter change
#   without a regeneration, or a render that produced no file, fails here.
case_deny contains {"file": s.file, "msg": sprintf("S1: %s is missing", [s.file])} if {
	some s in stills
	s.exists == false
}

# METADATA
# title: "S2 — a still is not blank"
# description: |
#   A render that drew nothing is one colour. The clock alone on its ground still
#   has lit, ghost and ground; a picture with fewer than three distinct colours
#   drew no surface.
case_deny contains {"file": s.file, "msg": sprintf("S2: %s has %d distinct colour(s) — nothing was drawn", [s.file, s.distinct])} if {
	some s in stills
	s.exists == true
	s.distinct < 3
}

# METADATA
# title: "S3 — a still sits on its variant's ground"
# description: |
#   The modal colour of a still is the variant's Window background (the harness's
#   window, where the clock and switcher sit) or its View background (what a
#   bound wallpaper or marquee draws as its own void). Anything else means the
#   picture was rendered under the wrong scheme.
case_deny contains {"file": s.file, "msg": sprintf("S3: %s has modal colour %s, not one of %v (variant %s)", [s.file, s.modal, s.grounds, s.variant])} if {
	some s in stills
	s.exists == true
	not s.modal in s.grounds
}

# METADATA
# title: "S4 — every planned animation exists with enough frames to move"
# description: |
#   The marquee animation is the harness's frames while the text is on the move;
#   fewer than ten is a still with a loop flag, not motion.
case_deny contains {"file": a.file, "msg": sprintf("S4: %s is missing", [a.file])} if {
	some a in anims
	a.exists == false
}

case_deny contains {"file": a.file, "msg": sprintf("S4: %s has %d frame(s) — not an animation", [a.file, a.frames])} if {
	some a in anims
	a.exists == true
	a.frames < 10
}

# METADATA
# title: "S5 — an animation never tears"
# description: |
#   A scroll is a left shift: each frame is the previous one moved left by at
#   most a quarter of the board, new content entering at the right. The
#   measurement finds the best shift per adjacent pair and the lit columns that
#   still disagree under it; a pair that disagrees beyond tolerance is a tear —
#   a rebuilt Row mid-scroll, a restart, frames out of order. The ring's wrap is
#   a left shift and passes.
case_deny contains {"file": a.file, "msg": sprintf("S5: %s tears at frame(s) %v", [a.file, [t.frame | some t in a.tears]])} if {
	some a in anims
	a.exists == true
	count(a.tears) > 0
}

# METADATA
# title: "S6 — an animation loops seamlessly"
# description: |
#   One item's whole run: the first and last frames are the same picture (the
#   empty board), so the loop closes without a jump (operator: "doesn't qualify
#   for r/perfectloops").
case_deny contains {"file": a.file, "msg": sprintf("S6: %s does not loop — its first and last frames differ", [a.file])} if {
	some a in anims
	a.exists == true
	a.seamless == false
}
