# METADATA
# title: "S0 — no planned stills admits nothing"
# description: |
#   The measurement is `scripts/check_screens.py --json` over the plan
#   catalog/library/render_screens.py declares (five surfaces x six variants).
package el.screens

import rego.v1

deny contains msg if {
	count(input.screens) == 0
	msg := "S0: no stills are planned"
}

# METADATA
# title: "S1 — every planned still exists"
# description: |
#   The pictures are checked in and regenerated by one script; an emitter change
#   without a regeneration, or a render that produced no file, fails here.
deny contains msg if {
	some s in input.screens
	not s.exists
	msg := sprintf("S1: %s is missing", [s.file])
}

# METADATA
# title: "S2 — a still is not blank"
# description: |
#   A render that drew nothing is one colour. The clock alone on its ground still
#   has lit, ghost and ground; a picture with fewer than three distinct colours
#   drew no surface.
deny contains msg if {
	some s in input.screens
	s.exists
	s.distinct < 3
	msg := sprintf("S2: %s has %d distinct colour(s) — nothing was drawn", [s.file, s.distinct])
}

# METADATA
# title: "S3 — a still sits on its variant's ground"
# description: |
#   The modal colour of a still is the variant's Window background (the harness's
#   window, where the clock and switcher sit) or its View background (what a
#   bound wallpaper or marquee draws as its own void). Anything else means the
#   picture was rendered under the wrong scheme.
deny contains msg if {
	some s in input.screens
	s.exists
	not s.modal in s.grounds
	msg := sprintf("S3: %s has modal colour %s, not one of %v (variant %s)", [s.file, s.modal, s.grounds, s.variant])
}

# METADATA
# title: "S4 — every planned animation exists with enough frames to move"
# description: |
#   The marquee animation is the harness's frames while the text is on the move;
#   fewer than ten is a still with a loop flag, not motion.
deny contains msg if {
	some a in input.animations
	not a.exists
	msg := sprintf("S4: %s is missing", [a.file])
}

deny contains msg if {
	some a in input.animations
	a.exists
	a.frames < 10
	msg := sprintf("S4: %s has %d frame(s) — not an animation", [a.file, a.frames])
}

# METADATA
# title: "S5 — an animation never tears"
# description: |
#   A scroll is a left shift: each frame is the previous one moved left by at
#   most a quarter of the board, new content entering at the right. The
#   measurement finds the best shift per adjacent pair and the lit columns that
#   still disagree under it; a pair that disagrees beyond tolerance is a tear —
#   a rebuilt Row mid-scroll, a restart, frames out of order. The ring's wrap is
#   a left shift and passes.
deny contains msg if {
	some a in input.animations
	a.exists
	count(a.tears) > 0
	msg := sprintf("S5: %s tears at frame(s) %v", [a.file, [t.frame | some t in a.tears]])
}

# METADATA
# title: "S6 — an animation loops seamlessly"
# description: |
#   One item's whole run: the first and last frames are the same picture (the
#   empty board), so the loop closes without a jump (operator: "doesn't qualify
#   for r/perfectloops").
deny contains msg if {
	some a in input.animations
	a.exists
	not a.seamless
	msg := sprintf("S6: %s does not loop — its first and last frames differ", [a.file])
}
