# SPDX-License-Identifier: Apache-2.0
# Stub: FontBuilder as make_font drives it (W255).
from fontTools.ttLib import Table, TTFont

class FontBuilder:
    font: TTFont
    def __init__(self, unitsPerEm: int | None = None, isTTF: bool = True) -> None: ...
    def setupGlyphOrder(self, glyphOrder: list[str]) -> None: ...
    def setupCharacterMap(self, cmapping: dict[int, str]) -> None: ...
    def setupGlyf(self, glyphs: dict[str, Table]) -> None: ...
    def setupHorizontalMetrics(self, metrics: dict[str, tuple[int, int]]) -> None: ...
    def setupHorizontalHeader(self, *, ascent: int, descent: int) -> None: ...
    def setupNameTable(self, nameStrings: dict[str, str]) -> None: ...
    def setupOS2(
        self,
        *,
        sTypoAscender: int,
        sTypoDescender: int,
        usWinAscent: int,
        usWinDescent: int,
    ) -> None: ...
    def setupPost(self, *, isFixedPitch: int) -> None: ...
