import QtQuick
import QtQuick.Layouts
import org.kde.plasma.plasmoid
import org.kde.plasma.plasma5support as P5Support
import org.kde.kirigami as Kirigami

// The operator's VictoriaMetrics, on the panel (W77). Generated by make_metrics.py;
// do not hand-edit.
//
// ⚑ THE ENDPOINT IS ASKED FOR, NEVER COPIED (luthen-observability contract,
// 2026-10-02): at start and on every retry the widget runs luthen's
// endpoints_query.py through the executable DataSource and builds the query URL
// from the JSON it prints ("answered" -> host, port). No host or port of luthen's
// appears in this file; policy/metrics.rego M3 refuses one.
//
// ⚑ NEVER BLANK (M2). Three faces, each with words:
//   endpoint-unavailable  the tool is absent (off-cluster: no luthen checkout) or
//                         refused (exit 1) or could not read its declaration (exit 2)
//   unreachable           the endpoint answered but the query failed
//   values                the query answered
PlasmoidItem {
    id: root
    Kirigami.Theme.colorSet: Kirigami.Theme.View
    Kirigami.Theme.inherit: false

    // the luthen tool and the query set are DATA from the emitter, not literals here
    readonly property string toolCommand: "$toolCommand"
    readonly property var queries: $queries
    readonly property int retryMs: $retryMs

    // the measured state (check_metrics reads these back)
    property string face: "endpoint-unavailable"
    property string faceText: "ENDPOINT UNAVAILABLE"
    property string endpoint: ""

    function setFace(f, text) {
        face = f
        faceText = text
    }

    // luthen's tool, run fresh each time - never cached into configuration
    P5Support.DataSource {
        id: tool
        engine: "executable"
        connectedSources: []
        onNewData: (source, data) => {
            disconnectSource(source)
            const code = data["exit code"]
            if (code !== 0) {
                root.endpoint = ""
                root.setFace("endpoint-unavailable", "ENDPOINT UNAVAILABLE")
                return
            }
            let doc = null
            try { doc = JSON.parse(data["stdout"]) } catch (e) { doc = null }
            if (!doc || doc.state !== "answered" || !doc.host || !doc.port) {
                root.endpoint = ""
                root.setFace("endpoint-unavailable", "ENDPOINT UNAVAILABLE")
                return
            }
            root.endpoint = "http://" + doc.host + ":" + doc.port
            root.queryAll()
        }
    }

    function resolve() {
        tool.connectSource(root.toolCommand)
    }

    function queryAll() {
        const parts = []
        let pending = root.queries.length
        let failed = false
        for (let i = 0; i < root.queries.length; i++) {
            const q = root.queries[i]
            const xhr = new XMLHttpRequest()
            xhr.onreadystatechange = function () {
                if (xhr.readyState !== XMLHttpRequest.DONE)
                    return
                let value = null
                if (xhr.status === 200) {
                    try {
                        const r = JSON.parse(xhr.responseText)
                        if (r.status === "success" && r.data.result.length > 0)
                            value = Number(r.data.result[0].value[1])
                    } catch (e) { value = null }
                }
                if (value === null)
                    failed = true
                else
                    parts[i] = q.label + " " + value.toFixed(q.digits)
                pending -= 1
                if (pending === 0) {
                    if (failed)
                        root.setFace("unreachable", "UNREACHABLE")
                    else
                        root.setFace("values", parts.join("  "))
                }
            }
            xhr.open("GET", root.endpoint + "/api/v1/query?query=" + encodeURIComponent(q.expr))
            xhr.send()
        }
    }

    Timer {
        interval: root.retryMs
        running: true
        repeat: true
        triggeredOnStart: true
        onTriggered: root.resolve()
    }

    fullRepresentation: Item {
        Layout.minimumWidth: label.implicitWidth
        Layout.minimumHeight: label.implicitHeight
        Text {
            id: label
            anchors.centerIn: parent
            text: root.faceText
            font.family: "monospace"
            color: root.face === "values" ? Kirigami.Theme.textColor : Kirigami.Theme.disabledTextColor
        }
    }
}
