// EL Openglo window switcher (⊕TASKSWITCH) — a phosphor departure board for Alt+Tab.
// Generated by make_taskswitch from templates/taskswitch-main.qml; the four colour
// holes are the variant's tokens (make_wallpaper_live.colors_for), nothing else is.
//
// The contract is KWin's own (read from /usr/share/kwin/tabbox/compact, Plasma
// 6.7): a KWin.TabBoxSwitcher root exposing currentIndex, a PlasmaCore.Dialog
// placed from screenGeometry, a ListView over tabBox.model whose roles are
// caption / icon / minimized, model.activate(i) on click, and the key handling
// on the dialog's main item because focus is lost on re-invocation.
import QtQuick
import QtQuick.Layouts
import org.kde.plasma.core as PlasmaCore
import org.kde.kirigami as Kirigami
import org.kde.plasma.components as PlasmaComponents3
import org.kde.kwin as KWin

KWin.TabBoxSwitcher {
    id: tabBox
    currentIndex: list.currentIndex

    // the palette: the selected row is LIT, the rest are the GHOST on the void
    property color litColor: "$lit"
    property color ghostColor: "$ghost"
    property color voidColor: "$ground"
    property real ghostAlpha: $ghostAlpha

    function itemCaption(caption, minimized) {
        return minimized ? "(" + caption + ")" : caption
    }

    TextMetrics {
        id: textMetrics
        property string longestCaption: tabBox.model?.longestCaption() || placeholderLabel.text
        text: itemCaption(longestCaption, true)
        font.bold: true
    }
    onVisibleChanged: {
        if (visible) {
            textMetrics.longestCaption = tabBox.model?.longestCaption() || placeholderLabel.text
        }
    }
    onModelChanged: {
        textMetrics.longestCaption = tabBox.model?.longestCaption() || placeholderLabel.text
    }

    Timer {
        id: activationTimer
        interval: Kirigami.Units.shortDuration
        onTriggered: tabBox.model.activate(list.currentIndex)
    }

    PlasmaCore.Dialog {
        id: dialog
        location: PlasmaCore.Types.Floating
        visible: tabBox.visible
        flags: Qt.Popup | Qt.X11BypassWindowManagerHint
        x: tabBox.screenGeometry.x + tabBox.screenGeometry.width * 0.5 - dialogMainItem.width * 0.5
        y: tabBox.screenGeometry.y + tabBox.screenGeometry.height * 0.5 - dialogMainItem.height * 0.5

        mainItem: Item {
            id: dialogMainItem

            property int pad: Kirigami.Units.largeSpacing
            property int optimalWidth: textMetrics.width + Kirigami.Units.iconSizes.small + 4 * pad
            property int optimalHeight: list.rowHeight * (list.count || 1) + 2 * pad
            width: Math.min(Math.max(tabBox.screenGeometry.width * 0.2, optimalWidth), tabBox.screenGeometry.width * 0.8)
            height: Math.min(optimalHeight, tabBox.screenGeometry.height * 0.8)

            // the board: void ground with a faint ghost bezel
            Rectangle {
                anchors.fill: parent
                color: tabBox.voidColor
                radius: dialogMainItem.pad
                border.width: 1
                border.color: tabBox.ghostColor
                opacity: 1.0
            }

            ListView {
                id: list
                property int rowHeight: Math.max(Kirigami.Units.iconSizes.small, textMetrics.height) + dialogMainItem.pad

                anchors.fill: parent
                anchors.margins: dialogMainItem.pad
                clip: true
                focus: true
                model: tabBox.model

                delegate: RowLayout {
                    id: row
                    required property int index
                    required property var model
                    required property string caption
                    required property bool minimized
                    readonly property bool current: index === list.currentIndex

                    width: list.width
                    height: list.rowHeight
                    spacing: dialogMainItem.pad

                    Accessible.name: captionItem.text
                    Kirigami.Icon {
                        source: row.model.icon
                        Layout.preferredWidth: Kirigami.Units.iconSizes.small
                        Layout.preferredHeight: Kirigami.Units.iconSizes.small
                        // an unselected entry recedes like an unlit segment
                        opacity: row.current ? 1.0 : tabBox.ghostAlpha
                    }
                    PlasmaComponents3.Label {
                        id: captionItem
                        text: tabBox.itemCaption(row.caption, row.minimized)
                        textFormat: Text.PlainText
                        elide: Text.ElideMiddle
                        color: row.current ? tabBox.litColor : tabBox.ghostColor
                        opacity: row.current ? 1.0 : (row.minimized ? tabBox.ghostAlpha * 0.75 : tabBox.ghostAlpha)
                        font.weight: row.current ? Font.Bold : Font.Normal
                        Layout.fillWidth: true
                    }
                    TapHandler {
                        onTapped: {
                            list.currentIndex = row.index
                            activationTimer.start()
                        }
                    }
                }

                // the lit row's bar: a segment-shaped highlight, no Breeze SVG
                highlight: Rectangle {
                    width: list.width
                    color: tabBox.litColor
                    opacity: 0.12
                    radius: dialogMainItem.pad / 2
                    border.width: 1
                    border.color: tabBox.litColor
                }
                highlightMoveDuration: 0
                highlightResizeDuration: 0
                boundsBehavior: Flickable.StopAtBounds
                Connections {
                    target: tabBox
                    function onCurrentIndexChanged() { list.currentIndex = tabBox.currentIndex }
                }

                RowLayout {
                    visible: list.count === 0
                    anchors.centerIn: parent
                    spacing: dialogMainItem.pad
                    Kirigami.Icon {
                        source: "edit-none"
                        Layout.preferredWidth: Kirigami.Units.iconSizes.small
                        Layout.preferredHeight: Kirigami.Units.iconSizes.small
                        opacity: tabBox.ghostAlpha
                    }
                    PlasmaComponents3.Label {
                        id: placeholderLabel
                        text: i18ndc("kwin", "@info:placeholder no entries in the task switcher", "No open windows")
                        textFormat: Text.PlainText
                        color: tabBox.ghostColor
                        Layout.fillWidth: true
                    }
                }
            }

            Keys.onPressed: event => {
                if (event.key === Qt.Key_Up || event.key === Qt.Key_Left) {
                    list.currentIndex = list.currentIndex === 0 ? list.count - 1 : list.currentIndex - 1
                } else if (event.key === Qt.Key_Down || event.key === Qt.Key_Right) {
                    list.currentIndex = list.currentIndex === list.count - 1 ? 0 : list.currentIndex + 1
                }
            }
        }

        onSceneGraphError: () => {
            // intentionally blank: QtQuick may qFatal() on a graphics reset otherwise
        }
    }
}
