#!/usr/bin/env python3
"""check_notify_roles.py — what the host's notification model actually EXPOSES (W46).

The marquee reads org.kde.notificationmanager's Notifications model. Its roles
(IdRole, UrgencyRole, PercentageRole, ...), enums (Urgency, JobState, Type) and
invokable methods (invokeAction, ...) are declared in the module's qmltypes,
generated by qmltyperegistrar from the C++ headers — the contract, on this host,
of everything W46 wants to read: urgency, actions, job progress. This parses
that file and reports the contract as a measurement; the widget and the harness
stub (check_marquee_live.STUB_MODEL) are held to it by policy/notify_roles.rego.

    scripts/check_notify_roles.py             # the roles, enums and methods, printed
    scripts/check_notify_roles.py --json      # the measurement
    scripts/check_notify_roles.py --selftest  # the parser can see

WEAKNESS: the qmltypes grammar is read by a small block parser (Component {
Enum { values: [...] } Method { name: } }), not by Qt's own tooling; a module
whose file is absent is withheld, not failed. ⚑ THE NUMBERS ARE DECLARATION
ORDINALS, NOT RUNTIME VALUES: the registrar writes enum NAMES in order and
drops the C++ values (Roles start at Qt::UserRole + 1 at runtime), so IdRole
reads 0 here and is 257 live. The widget reads every role SYMBOLICALLY
(NotificationManager.Notifications.IdRole), which is why the numbers never
matter to it — and why nothing here may be compared to a literal.
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
sys.path.insert(0, os.path.join(ROOT, "scripts"))
QMLTYPES = "/usr/lib64/qt6/qml/org/kde/notificationmanager/notificationmanager.qmltypes"


def _blocks(text, kind):
    """[(header_props, body)] for every `kind { ... }` block, brace-matched."""
    out = []
    for m in re.finditer(r"\b" + kind + r"\s*\{", text):
        depth, i = 1, m.end()
        while i < len(text) and depth:
            depth += {"{": 1, "}": -1}.get(text[i], 0)
            i += 1
        out.append(text[m.end():i - 1])
    return out


def _field(body, name):
    m = re.search(r'(?m)^\s*' + name + r':\s*"([^"]*)"', body)
    return m.group(1) if m else None


def parse(text):
    """{components: {name: {enums: {Enum: {key: value}}, methods: [name], properties: [name]}}}"""
    comps = {}
    for body in _blocks(text, "Component"):
        name = _field(body, "name")
        if not name:
            continue
        enums = {}
        for eb in _blocks(body, "Enum"):
            en = _field(eb, "name")
            vals = re.search(r"values:\s*\[([^\]]*)\]", eb, re.S)
            if en and vals:
                keys = re.findall(r'"([^"]+)"', vals.group(1))
                enums[en] = {k: i for i, k in enumerate(keys)}
                # explicit values, when the registrar wrote them as a map
                for k, v in re.findall(r'"([^"]+)":\s*(-?\d+)', vals.group(1)):
                    enums[en][k] = int(v)
        methods = [_field(mb, "name") for mb in _blocks(body, "Method")]
        props = [_field(pb, "name") for pb in _blocks(body, "Property")]
        comps[name] = {"enums": enums, "methods": [m for m in methods if m], "properties": [p for p in props if p],
                       "exports": re.findall(r'"([^"]+)"', (re.search(r"exports:\s*\[([^\]]*)\]", body) or re.search(r"()", "")).group(1))}
    return {"components": comps}


# the roles W46's capabilities read (catalog/notify-capabilities.md): identity and
# text (today), urgency, expiry, actions, job progress and state, type, transient,
# category, hints — every one must be declared by the host AND modelled by the stub
NEEDED = ("IdRole", "SummaryRole", "BodyRole", "ApplicationNameRole", "UrgencyRole", "ExpiredRole",
          "ActionNamesRole", "ActionLabelsRole", "PercentageRole", "JobStateRole", "TypeRole",
          "TransientRole", "CategoryRole", "HintsRole")


def measure(path=QMLTYPES):
    if not os.path.isfile(path):
        return {"withheld": f"{path} is not on this host", "roles": {}, "needed": list(NEEDED)}
    p = parse(open(path, encoding="utf-8").read())
    model = p["components"].get("NotificationManager::Notifications", {})
    roles = model.get("enums", {}).get("Roles", {})
    stub_text = ""
    try:
        import check_marquee_live as ML
        stub_text = ML.STUB_MODEL
    except Exception:
        pass
    stub_roles = set(re.findall(r"\b(\w+Role)\b", stub_text))
    return {"path": path, "roles": roles, "needed": list(NEEDED),
            "enums": {k: v for k, v in model.get("enums", {}).items() if k != "Roles"},
            "methods": model.get("methods", []),
            "stub_roles": sorted(stub_roles),
            "urgency": p["components"].get("NotificationManager::Notifications", {}).get("enums", {}).get("Urgency")
                       or next((c["enums"]["Urgency"] for c in p["components"].values() if "Urgency" in c["enums"]), None)}


def main(argv):
    known = {"--json", "--selftest"}
    for a in argv[1:]:
        if a not in known:
            print(f"check_notify_roles: unknown flag {a!r}", file=sys.stderr)
            return 2
    m = measure()
    if "--json" in argv:
        print(json.dumps(m, indent=1))
        return 0
    if "withheld" in m:
        print(f"check_notify_roles: WITHHELD — {m['withheld']}")
        return 0
    print(f"Notifications.Roles ({len(m['roles'])}; the number is the declaration ORDINAL, not the runtime value):")
    for k, v in m["roles"].items():
        print(f"    {k:28s} {v:2d}{'   (stub has it)' if k in m['stub_roles'] else '   STUB LACKS IT'}")
    for en, vals in m["enums"].items():
        print(f"enum {en}: {vals}")
    print(f"methods: {', '.join(m['methods'])}")
    missing = [r for r in NEEDED if r not in m["roles"]]
    print(f"check_notify_roles: {len(NEEDED) - len(missing)} of {len(NEEDED)} roles W46 needs are declared"
          + (f"; missing {missing}" if missing else "") + "; the verdict is `opa_gate.py notify_roles`")
    return 0


def _selftest():
    ok = True

    def chk(label, got, want):
        nonlocal ok
        print(f"  {'ok  ' if got == want else 'FAIL'} {label}" + ("" if got == want else f": got {got!r} want {want!r}"))
        ok = ok and got == want

    fixture = ('Module {\n  Component {\n    name: "NotificationManager::Notifications"\n'
               '    Enum {\n      name: "Roles"\n      values: ["IdRole", "UrgencyRole"]\n    }\n'
               '    Enum {\n      name: "Urgency"\n      values: ["LowUrgency", "NormalUrgency", "CriticalUrgency"]\n    }\n'
               '    Method { name: "invokeAction" }\n    Property { name: "count" }\n  }\n}\n')
    p = parse(fixture)["components"]["NotificationManager::Notifications"]
    chk("roles are read as an ordered enum", p["enums"]["Roles"], {"IdRole": 0, "UrgencyRole": 1})
    chk("a second enum is read", p["enums"]["Urgency"]["CriticalUrgency"], 2)
    chk("methods are read", p["methods"], ["invokeAction"])
    chk("an absent file is withheld", "withheld" in measure("/nonexistent.qmltypes"), True)
    print("check_notify_roles selftest:", "PASS" if ok else "FAIL")
    return ok


if __name__ == "__main__":
    if "--selftest" in sys.argv:
        sys.exit(0 if _selftest() else 1)
    sys.exit(main(sys.argv))
